services:
  # cripto-price-tracker:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3333:3333
  #   volumes:
  #     - ./:/app
  #   working_dir: /app
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db

  db:
    image: postgres
    restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: dev_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  test_db:
    image: postgres
    restart: always
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: test_db

volumes:
  postgres_data:
